import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { getAccess } from './authz.js';
const config=window.QURANER_ALO_CONFIG;const supabase=createClient(config.supabaseUrl,config.supabasePublishableKey,{auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:true}});const $=id=>document.getElementById(id);let students=[];let allStudents=[];let existing={};let access=null;let canManage=false;
const today=new Date().toISOString().slice(0,10);$('attendanceDate').value=today;$('attendanceDate').max=today;
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));}
function setFilterMsg(t,type=''){ $('filterMessage').textContent=t; $('filterMessage').className=`message-inline ${type}`.trim(); }
function setSaveMsg(t,type=''){ $('saveMessage').textContent=t; $('saveMessage').className=`message-inline ${type}`.trim(); }
async function loadSessions(){const date=$('attendanceDate').value;if(!date)return;let q=supabase.from('qa_class_sessions').select('session_id,teacher_id,course_code,session_date,starts_at,ends_at,topic,mode,status').eq('session_date',date).order('starts_at',{ascending:true});const teacher=$('teacherSelect').value;if(teacher)q=q.eq('teacher_id',teacher);const {data,error}=await q;if(error){setFilterMsg('Class session data load করা যায়নি।','error');return;}$('sessionSelect').innerHTML='<option value="">— session নির্বাচন করুন —</option>'+(data||[]).map(x=>{const time=x.starts_at?new Date(x.starts_at).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}):'—';return `<option value="${esc(x.session_id)}" data-course="${esc(x.course_code)}" data-topic="${esc(x.topic||'')}" data-teacher="${esc(x.teacher_id||'')}">${esc(time)} · ${esc(x.course_code)} · ${esc(x.topic||'Class')} · ${esc(x.status)}</option>`;}).join('');if(data?.length===1){$('sessionSelect').value=data[0].session_id;applySelectedSession();}}
function applySelectedSession(){const opt=$('sessionSelect').selectedOptions[0];if(!opt||!opt.value)return;$('courseCode').value=opt.dataset.course||'';$('topic').value=opt.dataset.topic||'';if(opt.dataset.teacher)$('teacherSelect').value=opt.dataset.teacher;}
async function init(){const a=await getAccess(supabase);if(!a){await supabase.auth.signOut();location.replace('./');return;}access=a;canManage=a.can('attendance.manage');if(!a.can('attendance.view')&&!canManage){$('loading').textContent='Attendance module-এর permission আপনার account-এ নেই।';return;}
const [tr,st]=await Promise.all([supabase.from('qa_teachers').select('teacher_id,full_name,teacher_code').eq('active',true).order('full_name'),supabase.from('qa_students').select('student_id,student_code,full_name,phone').eq('status','active').order('full_name')]);if(tr.error||st.error){setFilterMsg('Required records load করা যায়নি।','error');return;}$('teacherSelect').innerHTML='<option value="">— নির্ধারিত নয় —</option>'+tr.data.map(t=>`<option value="${esc(t.teacher_id)}">${esc(t.teacher_code)} · ${esc(t.full_name)}</option>`).join('');allStudents=st.data||[];students=allStudents;$('loading').classList.add('hidden');$('app').classList.remove('hidden');await loadSessions();await loadAttendance();}

async function scopeStudentsToTeacher(){const teacherId=$('teacherSelect').value;if(!teacherId){students=allStudents;return;}const [{data:direct,error:de},{data:gs,error:ge}]=await Promise.all([supabase.from('qa_students').select('student_id').eq('teacher_id',teacherId).eq('status','active'),supabase.from('qa_study_groups').select('group_id').eq('teacher_id',teacherId).eq('active',true)]);if(de||ge)throw(de||ge);const ids=new Set((direct||[]).map(x=>x.student_id));const gids=(gs||[]).map(x=>x.group_id);if(gids.length){const{data:ms,error}=await supabase.from('qa_group_memberships').select('student_id').in('group_id',gids).is('left_at',null);if(error)throw error;(ms||[]).forEach(x=>ids.add(x.student_id));}students=allStudents.filter(s=>ids.has(s.student_id));}
async function loadAttendance(){const date=$('attendanceDate').value;if(!date)return;await scopeStudentsToTeacher();const sessionId=$('sessionSelect').value||null;setFilterMsg('Attendance data load হচ্ছে…');let q=supabase.from('qa_attendance').select('attendance_id,session_id,student_id,teacher_id,status,remarks,attendance_date').eq('attendance_date',date);if(sessionId)q=q.eq('session_id',sessionId);else q=q.is('session_id',null);const {data,error}=await q;if(error){setFilterMsg('Attendance data load করা যায়নি।','error');return;}existing=Object.fromEntries((data||[]).map(r=>[r.student_id,r]));renderRows();setFilterMsg(`${students.length} জন শিক্ষার্থী প্রস্তুত।`);}
function renderRows(){const canEdit=canManage;$('attendanceRows').innerHTML=students.map(s=>{const r=existing[s.student_id]||{};return `<tr data-id="${esc(s.student_id)}"><td><strong>${esc(s.student_code)}</strong></td><td>${esc(s.full_name)}</td><td>${esc(s.phone)}</td><td><select data-status ${canEdit?'':'disabled'}><option value="" ${!r.status?'selected':''}>Not Recorded</option><option value="present" ${r.status==='present'?'selected':''}>Present</option><option value="absent" ${r.status==='absent'?'selected':''}>Absent</option><option value="late" ${r.status==='late'?'selected':''}>Late</option><option value="excused" ${r.status==='excused'?'selected':''}>Excused</option><option value="leave" ${r.status==='leave'?'selected':''}>Leave</option><option value="class_cancelled" ${r.status==='class_cancelled'?'selected':''}>Class Cancelled</option></select></td><td><input data-remarks value="${esc(r.remarks||'')}" ${canEdit?'':'disabled'}></td></tr>`;}).join('');$('studentCount').textContent=`${students.length} students`;$('saveAttendance').classList.toggle('hidden',!canEdit);}
$('filterForm').addEventListener('submit',async e=>{e.preventDefault();await loadSessions();await loadAttendance();});$('teacherSelect').addEventListener('change',async()=>{await loadSessions();await loadAttendance();});$('attendanceDate').addEventListener('change',async()=>{await loadSessions();});$('sessionSelect').addEventListener('change',async()=>{applySelectedSession();await loadAttendance();});
$('saveAttendance').addEventListener('click',async()=>{if(!canManage){setSaveMsg('Attendance manage permission নেই।','error');return;}const date=$('attendanceDate').value;if(date>today){setSaveMsg('Future date-এর attendance save করা যাবে না।','error');return;}const sessionId=$('sessionSelect').value||null;const teacherId=$('teacherSelect').value||null;if(sessionId&&!teacherId){setSaveMsg('Selected session-এর Teacher নির্ধারিত নেই। Save করা যাবে না।','error');return;}const courseCode=$('courseCode').value.trim();const topic=$('topic').value.trim();const sessionNote=$('sessionNote').value.trim();const rows=[...document.querySelectorAll('#attendanceRows tr')];$('saveAttendance').disabled=true;setSaveMsg('Saving attendance…');let saved=0;for(const row of rows){const studentId=row.dataset.id;const status=row.querySelector('[data-status]').value;const remarks=row.querySelector('[data-remarks]').value.trim();const old=existing[studentId];if(!status)continue;if(old&&old.status===status&&(old.remarks||'')===remarks&&(old.teacher_id||null)===(teacherId||null)&&(old.session_id||null)===(sessionId||null))continue;let result;if(old){result=await supabase.from('qa_attendance').update({session_id:sessionId,teacher_id:teacherId,status,remarks,updated_at:new Date().toISOString()}).eq('attendance_id',old.attendance_id);}else{result=await supabase.from('qa_attendance').insert({session_id:sessionId,student_id:studentId,teacher_id:teacherId,attendance_date:date,status,remarks});}if(!result.error){saved++;if(old)existing[studentId]={...old,session_id:sessionId,teacher_id:teacherId,status,remarks};}}
if(!sessionId&&teacherId&&courseCode){const {data:existingSession}=await supabase.from('qa_class_sessions').select('session_id').eq('teacher_id',teacherId).eq('session_date',date).eq('course_code',courseCode).order('created_at',{ascending:false}).limit(1).maybeSingle();if(existingSession?.session_id)await supabase.from('qa_class_sessions').update({topic:topic||null,notes:sessionNote,status:'completed',updated_at:new Date().toISOString()}).eq('session_id',existingSession.session_id);else await supabase.from('qa_class_sessions').insert({teacher_id:teacherId,course_code:courseCode,session_date:date,topic:topic||null,notes:sessionNote,status:'completed'});}
$('saveAttendance').disabled=false;setSaveMsg(`${saved}টি attendance record save হয়েছে।`,'success');await loadAttendance();});
$('signOut').addEventListener('click',async()=>{await supabase.auth.signOut();location.replace('./');});await init();