import {createClient} from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import {getAccess} from './authz.js';
import {readAll} from './ui-data.js?v=20261001-fixes2';
import {searchableSelect} from './ui-forms.js?v=20261001-fixes2';
import {locale,t} from './ui-i18n.js?v=20261001-fixes2';
const $=id=>document.getElementById(id),config=window.QURANER_ALO_CONFIG,db=createClient(config.supabaseUrl,config.supabasePublishableKey);
if(new URLSearchParams(location.search).get('embed')==='1')document.body.classList.add('qa-id-embedded');
const roles={student:['qa_students','student_id','student_code','students','Student'],teacher:['qa_teachers','teacher_id','teacher_code','teachers','Teacher'],helper:['qa_staff','staff_id','staff_code','staff','Helper']};
const kinds=[['completion','Course Completion Certificate','কোর্স সমাপ্তির সনদ'],['academic','Academic Achievement Certificate','শিক্ষাগত অর্জনের সনদ'],['testimonial','Testimonial','প্রশংসাপত্র'],['character','Character Certificate','চারিত্রিক সনদ'],['transfer','Transfer Certificate','ছাড়পত্র'],['status','Student Status Certificate','অধ্যয়নরত শিক্ষার্থীর প্রত্যয়নপত্র'],['attendance','Attendance Certificate','উপস্থিতির সনদ'],['participation','Participation Certificate','অংশগ্রহণের সনদ'],['appreciation','Certificate of Appreciation','সম্মাননা সনদ'],['experience','Experience Certificate','অভিজ্ঞতার সনদ'],['custom','Other Certificate','অন্যান্য সনদ']];
let people=[],school={},loadToken=0;
const bn=()=>$('certificateLanguage').value==='bn',name=p=>bn()?(p.full_name_bn||p.full_name):(p.full_name||p.full_name_bn),node=(tag,text,cls)=>{const e=document.createElement(tag);if(text)e.textContent=text;if(cls)e.className=cls;return e};
function invalidate(){$('printCertificate').disabled=true;$('certificatePreview').classList.add('hidden')}
function updateTypes(){const old=$('certificateType').value,staff=$('certificateRole').value!=='student';$('certificateType').replaceChildren(...kinds.filter(k=>staff?['experience','character','participation','appreciation','custom'].includes(k[0]):k[0]!=='experience').map(k=>{const o=node('option',k[bn()?2:1]);o.value=k[0];return o}));if([...$('certificateType').options].some(o=>o.value===old))$('certificateType').value=old;template()}
function template(){invalidate();const person=people.find(p=>p[roles[$('certificateRole').value][1]]===$('certificatePerson').value);if(!person){$('certificateText').value='';return}const who=name(person),schoolName=bn()?school.name_bn:school.name_en;const statements=bn()?{completion:`এই মর্মে প্রত্যয়ন করা যাচ্ছে যে, ${who} ${schoolName}-এ [কোর্সের নাম] কোর্সটি [সমাপ্তির তারিখ]-এ সফলভাবে সম্পন্ন করেছেন।`,academic:`${who}-কে [পরীক্ষা / অর্জনের বিবরণ]-এ কৃতিত্বের স্বীকৃতিস্বরূপ এই সনদ প্রদান করা হলো।`,testimonial:`এই মর্মে প্রত্যয়ন করা যাচ্ছে যে, ${who} ${schoolName}-এর একজন শিক্ষার্থী। [প্রাসঙ্গিক তথ্য লিখুন]`,character:`এই মর্মে প্রত্যয়ন করা যাচ্ছে যে, ${who}-এর আচরণ ও চারিত্রিক মূল্যায়ন: [যাচাইকৃত বিবরণ লিখুন]।`,transfer:`${who}-কে [ছাড়পত্রের তারিখ] থেকে ছাড়পত্র প্রদান করা হলো। শ্রেণি / কোর্স: [লিখুন]। প্রয়োজনীয় বিবরণ: [লিখুন]।`,status:`এই মর্মে প্রত্যয়ন করা যাচ্ছে যে, ${who} ${schoolName}-এ [শ্রেণি / কোর্স]-এ অধ্যয়নরত আছেন। শিক্ষাবর্ষ: [লিখুন]।`,attendance:`${who}-এর [সময়সীমা]-তে উপস্থিতি: [উপস্থিত দিনের সংখ্যা] / [মোট কার্যদিবস]।`,participation:`${who} [অনুষ্ঠান / প্রতিযোগিতার নাম]-এ [তারিখ]-এ অংশগ্রহণ করেছেন।`,appreciation:`${who}-কে [অবদান / অর্জনের বিবরণ]-এর স্বীকৃতিস্বরূপ এই সম্মাননা প্রদান করা হলো।`,experience:`এই মর্মে প্রত্যয়ন করা যাচ্ছে যে, ${who} ${schoolName}-এ [পদ]-এ [শুরুর তারিখ] থেকে [শেষ তারিখ] পর্যন্ত কর্মরত ছিলেন / আছেন।`,custom:`${who} সম্পর্কে সনদের বিবরণ লিখুন।`}:{completion:`This certifies that ${who} successfully completed [course name] at ${schoolName} on [completion date].`,academic:`This certificate recognizes ${who} for [verified academic achievement].`,testimonial:`This is to certify that ${who} is a student of ${schoolName}. [Enter relevant verified details.]`,character:`This certifies the following assessment of ${who}'s conduct and character: [enter verified details].`,transfer:`A transfer certificate is issued to ${who} effective [date]. Class / course: [enter]. Additional details: [enter].`,status:`This certifies that ${who} is studying in [class / course] at ${schoolName} during [academic year].`,attendance:`Attendance for ${who} during [period]: [days attended] out of [total working days].`,participation:`This recognizes ${who}'s participation in [event] on [date].`,appreciation:`This certificate is presented to ${who} in recognition of [contribution / achievement].`,experience:`This certifies that ${who} worked / has been working at ${schoolName} as [role] from [start date] to [end date].`,custom:`Enter the certificate details for ${who}.`};$('certificateText').value=statements[$('certificateType').value]||''}
async function load(){const token=++loadToken;invalidate();$('certificatePerson').replaceChildren(node('option',''));const r=roles[$('certificateRole').value];const {data,error}=await readAll(()=>db.from(r[0]).select(r[1]+','+r[2]+',full_name,full_name_bn').order(r[1]));if(token!==loadToken)return;if(error){$('errorBox').textContent=t('Unable to load students.');$('errorBox').classList.remove('hidden');return}people=data||[];for(const p of people){const o=node('option',(p.full_name||'')+' · '+(p.full_name_bn||'')+' · '+p[r[2]]);o.value=p[r[1]];$('certificatePerson').append(o)}$('certificatePerson').dispatchEvent(new Event('change'));updateTypes()}
$('certificateRole').onchange=load;$('certificatePerson').addEventListener('change',template);$('certificateType').onchange=template;$('certificateLanguage').onchange=updateTypes;
$('certificateForm').addEventListener('input',invalidate);
$('certificateForm').onsubmit=e=>{e.preventDefault();const role=roles[$('certificateRole').value],p=people.find(p=>p[role[1]]===$('certificatePerson').value);if(!p)return;const box=$('certificatePreview');box.replaceChildren();box.lang=bn()?'bn':'en';const head=node('header'),logo=node('img');logo.src=school.logo_path||'assets/quraner-alo-logo.jpg';logo.alt='';const schoolText=node('div');schoolText.append(node('h2',bn()?school.name_bn:school.name_en),node('p',[school.address,school.phone].filter(Boolean).join(' · ')));head.append(logo,schoolText);const meta=node('div',null,'certificate-meta');meta.append(node('span',($('certificateNumber').value? (bn()?'সনদ নম্বর: ':'Certificate No: ')+$('certificateNumber').value:'')),node('span',(bn()?'তারিখ: ':'Date: ')+$('certificateDate').value));box.append(head,meta,node('h1',$('certificateType').selectedOptions[0].textContent),node('p',name(p),'certificate-name'),node('p',p[role[2]],'certificate-code'),node('p',$('certificateText').value,'certificate-body'),node('footer',[$('certificateSigner').value,bn()?'অনুমোদনকারী কর্তৃপক্ষ':'Authorized Signatory'].filter(Boolean).join('\n')));box.classList.remove('hidden');$('printCertificate').disabled=false;};
$('printCertificate').onclick=async()=>{await document.fonts.ready;await Promise.all([...$('certificatePreview').querySelectorAll('img')].map(i=>i.decode().catch(()=>{})));window.print()};$('signOut').onclick=async()=>{await db.auth.signOut();location.replace('./')};
(async()=>{try{const access=await getAccess(db);if(!access)throw Error(t('Please sign in'));const allowed=Object.entries(roles).filter(([,r])=>access.can(r[3]+'.view')||access.can(r[3]+'.manage'));if(!allowed.length)throw Error(t('No permission'));$('certificateRole').replaceChildren(...allowed.map(([value,r])=>{const o=node('option',t(r[4]));o.value=value;return o}));const result=await db.from('qa_app_settings').select('value').eq('key','school_profile').maybeSingle();school={name_bn:'কোরআনের আলো',name_en:'QURANER ALO',...result.data?.value};$('certificateLanguage').value=locale();$('certificateDate').value=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Dhaka'});searchableSelect($('certificatePerson'));await load();$('loading').classList.add('hidden');$('app').classList.remove('hidden')}catch(e){$('loading').classList.add('hidden');$('errorBox').textContent=e.message;$('errorBox').classList.remove('hidden')}})();
