import {createClient} from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import {getAccess} from './authz.js';
import {readAll} from './ui-data.js?v=20261001-fourstep1';
import {t,locale,personName,setLanguage} from './ui-i18n.js?v=20261001-fourstep1';
import {getProfileImage,fetchDocumentBlob} from './documents-client.js';
const c=window.QURANER_ALO_CONFIG,supabase=createClient(c.supabaseUrl,c.supabasePublishableKey),$=id=>document.getElementById(id),el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n};
const embedded=new URLSearchParams(location.search).get('embed')==='1';if(embedded)document.body.classList.add('qa-id-embedded');
const types={student:{table:'qa_students',id:'student_id',code:'student_code',date:'admission_date',permission:'students',label:'Student'},teacher:{table:'qa_teachers',id:'teacher_id',code:'teacher_code',date:'joining_date',permission:'teachers',label:'Teacher'},helper:{table:'qa_staff',id:'staff_id',code:'staff_code',date:'joining_date',permission:'staff',label:'Helper'}};
let people=[],school={name_bn:'কোরআনের আলো',name_en:'QURANER ALO',logo_path:'assets/quraner-alo-logo.jpg'},selected=new Set(),access,loadId=0;const pictures=new Map();
const photoPromises=new Map();
function loadPhoto(role,id){const key=role+id;if(pictures.has(key))return Promise.resolve(pictures.get(key));if(photoPromises.has(key))return photoPromises.get(key);const promise=getProfileImage({role,personId:id}).then(async result=>{if(!result?.found||!result.file?.documentToken){pictures.set(key,null);return null}const file=await fetchDocumentBlob(result.file.documentToken);const url=URL.createObjectURL(file.blob);pictures.set(key,url);return url}).catch(()=>{pictures.set(key,null);return null});photoPromises.set(key,promise);return promise;}
const photoObserver=new IntersectionObserver(entries=>{for(const entry of entries){if(!entry.isIntersecting)continue;photoObserver.unobserve(entry.target);const role=entry.target.dataset.role,id=entry.target.dataset.personId;loadPhoto(role,id).then(url=>{if(url)for(const image of document.querySelectorAll('.qa-id-photo'))if(image.dataset.role===role&&image.dataset.personId===id)image.src=url;});}},{rootMargin:'100px'});

function render(){const role=$('cardRole').value,type=types[role];if(!type)return;const query=$('cardSearch').value.trim().toLowerCase(),rows=people.filter(p=>[p.full_name,p.full_name_bn,p[type.code]].some(v=>String(v||'').toLowerCase().includes(query)));photoObserver.disconnect();$('idCards').replaceChildren();for(const p of rows){const id=p[type.id],card=el('article',null,'qa-id-card'+(selected.has(id)?' is-selected':'')),header=el('header'),logo=el('img');logo.src=school.logo_path||'assets/quraner-alo-logo.jpg';logo.alt='';const title=el('div');title.append(el('h2',locale()==='bn'?school.name_bn:school.name_en,'qa-record-name'),el('p',t(type.label)+' · '+t('ID Cards')));header.append(logo,title);card.append(header);const checkLabel=el('label',null,'qa-id-check'),check=el('input');check.type='checkbox';check.checked=selected.has(id);check.setAttribute('aria-label',t('Select')+' '+personName(p));check.onchange=()=>{if(check.checked)selected.add(id);else selected.delete(id);card.classList.toggle('is-selected',check.checked);count()};checkLabel.append(check,el('span',t('Select')));card.append(checkLabel);const photo=el('img',null,'qa-id-photo');photo.alt=personName(p);photo.dataset.role=role;photo.dataset.personId=id;photo.src=pictures.get(role+id)||school.logo_path||'assets/quraner-alo-logo.jpg';card.append(photo,el('h3',personName(p),'qa-record-name'),el('div',p[type.code],'qa-id-code qa-record-name'));const dl=el('dl');for(const [label,value] of [['Role',t(type.label)],[role==='student'?'Admission date':'Joining date',p[type.date]||'—'],['Phone',p.phone||'—']]){const row=el('div');row.append(el('dt',t(label)),el('dd',value,'qa-record-name'));dl.append(row)}card.append(dl,el('footer',[school.address,school.phone].filter(Boolean).join('\n'),'qa-record-name'));$('idCards').append(card);if(!pictures.has(role+id))photoObserver.observe(photo)}if(!rows.length)$('idCards').append(el('p',t('No records found')));count();$('selectAllCards').checked=rows.length>0&&rows.every(p=>selected.has(p[type.id]));}
function count(){$('cardCount').textContent=`${selected.size} · ${t('Selected')}`;$('printCards').disabled=!selected.size;}
async function load(){const token=++loadId,role=$('cardRole').value,type=types[role];if(!type||!(access.can(type.permission+'.view')||access.can(type.permission+'.manage')))return;selected.clear();$('idCards').textContent=t('Loading…');let build=()=>{let q=supabase.from(type.table).select(`${type.id},${type.code},full_name,full_name_bn,phone,${type.date}`).order(type.id);return role==='helper'?q.eq('staff_type','helper'):q};const {data,error}=await readAll(build);if(token!==loadId)return;if(error){$('idCards').textContent=t('Unable to load ID cards');return}people=data||[];render();}
$('cardRole').onchange=load;$('cardSearch').oninput=render;$('cardLanguage').onchange=()=>setLanguage($('cardLanguage').value);$('selectAllCards').onchange=()=>{const type=types[$('cardRole').value],query=$('cardSearch').value.toLowerCase();people.filter(p=>[p.full_name,p.full_name_bn,p[type.code]].some(v=>String(v||'').toLowerCase().includes(query))).forEach(p=>{if($('selectAllCards').checked)selected.add(p[type.id]);else selected.delete(p[type.id])});render()};$('printCards').onclick=async()=>{const button=$('printCards');button.disabled=true;const role=$('cardRole').value;try{await Promise.all([...selected].map(id=>loadPhoto(role,id)));$('cardSearch').value='';render();await Promise.all([...document.querySelectorAll('.qa-id-card.is-selected img')].map(image=>image.decode().catch(()=>{})));window.print()}finally{button.disabled=!selected.size}};$('signOut').onclick=async()=>{await supabase.auth.signOut();location.replace('./')};window.addEventListener('qa-language-change',()=>{$('cardLanguage').value=locale();render()});
(async()=>{try{access=await getAccess(supabase);if(!access)throw new Error(t('Please sign in'));const allowed=Object.entries(types).filter(([,type])=>access.can(type.permission+'.view')||access.can(type.permission+'.manage'));if(!allowed.length)throw new Error(t('No permission'));$('cardRole').replaceChildren(...allowed.map(([value,type])=>{const o=el('option',t(type.label));o.value=value;return o}));const {data}=await supabase.from('qa_app_settings').select('value').eq('key','school_profile').maybeSingle();school={...school,...data?.value};$('cardLanguage').value=locale();$('loading').classList.add('hidden');$('app').classList.remove('hidden');await load()}catch(e){$('loading').classList.add('hidden');$('errorBox').textContent=e.message;$('errorBox').classList.remove('hidden')}})();
