import {readAll} from './ui-data.js?v=20261001-fixes2';
import {createClient} from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { getAccess } from './authz.js';
const c=window.QURANER_ALO_CONFIG;const supabase=createClient(c.supabaseUrl,c.publishableKey||c.supabasePublishableKey,{auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:true}});const $=id=>document.getElementById(id);let employees=[];let employeeMap={};let payroll=[];let canManage=false;let canFinanceManage=false;
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));}function money(v){return Number(v||0).toFixed(2)}function msg(t,type=''){ $('message').textContent=t;$('message').className=`message-inline ${type}`.trim();}function setAccordion(buttonId,bodyId,openLabel,closeLabel,open){const button=$(buttonId),body=$(bodyId);if(!button||!body)return;body.classList.toggle('hidden',!open);button.setAttribute('aria-expanded',String(open));button.innerHTML=(open?closeLabel:openLabel)+' <span aria-hidden="true">'+(open?'⌃':'⌄')+'</span>';}
function calc(){const basic=+($('basic').value||0),a=+($('allowance').value||0),b=+($('bonus').value||0),o=+($('overtime').value||0),d=+($('deduction').value||0),l=+($('leaveDeduction').value||0),ad=+($('advance').value||0),adj=+($('adjustment').value||0);$('net').textContent=money(basic+a+b+o+adj-d-l-ad);return basic+a+b+o+adj-d-l-ad;}
function setFormEnabled(enabled){$('payrollForm').querySelectorAll('input,select,textarea,button[type="submit"]').forEach(el=>el.disabled=!enabled)}
async function init(){const access=await getAccess(supabase);if(!access){await supabase.auth.signOut();location.replace('./');return;}canManage=access.can('payroll.manage');canFinanceManage=access.can('finance.manage');if(!access.can('payroll.view')&&!canManage){$('loading').textContent='Payroll module-এর permission আপনার account-এ নেই।';return;}setFormEnabled(canManage);$('expenseForm').querySelectorAll('input,select,textarea,button[type="submit"]').forEach(el=>el.disabled=!canFinanceManage);const [{data:t,error:te},{data:s,error:se}]=await Promise.all([supabase.from('qa_teachers').select('teacher_id,user_id,teacher_code,full_name').eq('active',true).order('full_name'),supabase.from('qa_staff').select('staff_id,user_id,staff_code,full_name').eq('active',true).eq('staff_type','helper').order('full_name')]);if(te||se){msg('Employee list load করা যায়নি।','error');return;}employees=[...(t||[]).map(x=>({...x,refId:x.teacher_id,userId:x.user_id,code:x.teacher_code,type:'teacher',labelType:'Teacher'})),...(s||[]).map(x=>({...x,refId:x.staff_id,userId:x.user_id,code:x.staff_code,type:'helper',labelType:'Helper'}))];employeeMap=Object.fromEntries(employees.map(x=>[x.type+'|'+x.refId,x.code+' · '+x.full_name+' ('+x.labelType+')']));$('employeeSelect').innerHTML='<option value="">Employee নির্বাচন করুন</option>'+employees.map(x=>`<option value="${esc(x.type+'|'+x.refId)}">${esc(x.code)} · ${esc(x.full_name)} (${esc(x.labelType)})</option>`).join('');$('payrollMonth').value=new Date().toISOString().slice(0,7);$('expenseDate').value=new Date().toISOString().slice(0,10);$('loading').classList.add('hidden');$('app').classList.remove('hidden');await refresh();}
async function refresh(silent=false){window.dispatchEvent(new CustomEvent('qa-finance-refresh'));const {data,error}=await readAll(()=>supabase.from('qa_payroll_records').select('payroll_id,employee_user_id,employee_type,employee_ref_id,employee_code_snapshot,employee_name_snapshot,payroll_month,basic,allowance,bonus,overtime,deduction,leave_deduction,advance,adjustment,net_payable,status,paid_at,payment_method,payment_reference,notes').order('payroll_month',{ascending:false}).order('payroll_id'));if(error){if(!silent)msg('Payroll ledger load করা যায়নি।','error');throw error;}payroll=data||[];$('count').textContent=`${payroll.length} records`;$('rows').innerHTML=payroll.map(x=>{const adds=Number(x.allowance)+Number(x.bonus)+Number(x.overtime);const reductions=Number(x.deduction)+Number(x.leave_deduction)+Number(x.advance);return `<tr><td>${esc(x.payroll_month)}</td><td>${esc(employeeMap[x.employee_type+'|'+x.employee_ref_id]||(x.employee_code_snapshot+' · '+x.employee_name_snapshot))}</td><td>৳${money(x.basic)}</td><td>৳${money(adds)}</td><td>৳${money(reductions)}</td><td><strong>৳${money(x.net_payable)}</strong></td><td><select class="status-select" data-id="${esc(x.payroll_id)}" ${canManage?'':'disabled'}><option ${x.status==='draft'?'selected':''}>draft</option><option ${x.status==='reviewed'?'selected':''}>reviewed</option><option ${x.status==='approved'?'selected':''}>approved</option><option ${x.status==='paid'?'selected':''}>paid</option><option ${x.status==='cancelled'?'selected':''}>cancelled</option></select></td><td><button class="save-btn" data-save="${esc(x.payroll_id)}" ${canManage?'':'disabled'}>Save</button></td></tr>`}).join('');document.querySelectorAll('[data-save]').forEach(btn=>btn.addEventListener('click',()=>updateStatus(btn.dataset.save)));}
async function updateStatus(id){if(!canManage){msg('Payroll manage permission নেই।','error');return;}const select=document.querySelector(`[data-id="${CSS.escape(id)}"]`);const status=select?.value;if(!status)return;const patch={status};if(status==='paid')patch.paid_at=new Date().toISOString();const {error}=await supabase.from('qa_payroll_records').update(patch).eq('payroll_id',id);if(error){msg('Payroll status update করা যায়নি।','error');return;}msg('Payroll status updated।','success');await refresh();}
['basic','allowance','bonus','overtime','deduction','leaveDeduction','advance','adjustment'].forEach(id=>$(id).addEventListener('input',calc));
$('payrollForm').addEventListener('submit',async e=>{e.preventDefault();if(!canManage){msg('Payroll manage permission নেই।','error');return;}msg('Saving…');const parts=String($('employeeSelect').value||'|').split('|');const employee=employees.find(x=>x.type===parts[0]&&x.refId===parts[1]);if(!employee){msg('Employee নির্বাচন করুন।','error');return;}const row={employee_user_id:employee.userId||null,employee_type:employee.type,employee_ref_id:employee.refId,employee_code_snapshot:employee.code,employee_name_snapshot:employee.full_name,payroll_month:`${$('payrollMonth').value}-01`,basic:+($('basic').value||0),allowance:+($('allowance').value||0),bonus:+($('bonus').value||0),overtime:+($('overtime').value||0),deduction:+($('deduction').value||0),leave_deduction:+($('leaveDeduction').value||0),advance:+($('advance').value||0),adjustment:+($('adjustment').value||0),notes:$('notes').value.trim()};const {error}=await supabase.from('qa_payroll_records').insert(row);if(error){msg(error.code==='23505'?'এই employee-এর এই মাসের payroll record আগে থেকেই আছে।':'Payroll save করা যায়নি। '+(error.message||''),'error');return;}msg('Payroll record সফলভাবে save হয়েছে।','success');e.target.reset();$('payrollMonth').value=new Date().toISOString().slice(0,7);calc();try{await refresh(true);}catch(refreshError){console.error(refreshError);msg('Payroll save হয়েছে; ledger refresh হয়নি।','error');}});
$('toggleExpenseEntry')?.addEventListener('click',()=>{const open=$('toggleExpenseEntry').getAttribute('aria-expanded')!=='true';setAccordion('toggleExpenseEntry','expenseEntryBody','Open New Expense','Close New Expense',open);});
$('expenseForm')?.addEventListener('submit',async e=>{e.preventDefault();const el=$('expenseMessage');const say=(t,type='')=>{el.textContent=t;el.className='message-inline '+type};if(!canFinanceManage){say('Expense manage permission নেই।','error');return;}say('Expense saving হচ্ছে…');const row={transaction_date:$('expenseDate').value,direction:'expense',category:$('expenseCategory').value.trim(),amount:+$('expenseAmount').value,account_name:$('expenseAccount').value,reference:$('expenseReference').value.trim()||null,description:$('expenseDescription').value.trim()};const{error}=await supabase.from('qa_finance_transactions').insert(row);if(error){console.error(error);say('Expense save করা যায়নি।','error');return;}say('Expense সফলভাবে save হয়েছে। সংশ্লিষ্ট Voucher central Voucher List-এ পাওয়া যাবে।','success');e.target.reset();$('expenseDate').value=new Date().toISOString().slice(0,10);});

$('signOut').addEventListener('click',async()=>{await supabase.auth.signOut();location.replace('./');});init();
