import {t,locale} from './ui-i18n.js';
const $=id=>document.getElementById(id);
function node(tag,cls,text){const e=document.createElement(tag);if(cls)e.className=cls;if(text!=null)e.textContent=text;return e;}
function storage(k,v){try{if(v!=null)localStorage.setItem(k,v);else return localStorage.getItem(k);}catch{}}
function fields(row,headers){const grid=node('div','qa-card-fields');[...row.cells].slice(2).forEach((cell,index)=>{if(cell.querySelector('button,a,select')||cell.colSpan>1)return;const item=node('div');item.append(node('span','',headers[index+2]?.textContent||''),node('b','qa-record-name',['gender','status','marital','portal'].includes(cell.dataset.col)?t(cell.textContent.trim()||'—'):cell.textContent.trim()||'—'));grid.append(item);});return grid;}
function rail(row,headers){document.querySelector('.qa-details-rail')?.remove();const box=node('aside','qa-details-rail');box.setAttribute('aria-label',t('Details'));const close=node('button','', '×');close.type='button';close.setAttribute('aria-label',t('Close'));close.onclick=()=>{box.remove();document.body.classList.remove('qa-details-open')};box.append(close,node('p','qa-card-code qa-record-name',row.cells[0]?.textContent),node('h2','qa-record-name',row.cells[1]?.textContent),fields(row,headers));const href=row.querySelector('a[href*="profile.html"]')?.href;if(href){const a=node('a','',t('Open Profile'));a.href=href;box.append(a)}document.body.append(box);document.body.classList.add('qa-details-open');close.focus();}
export function initLists(){for(const id of ['studentRows','staffRows']){const tbody=$(id);if(!tbody)continue;const table=tbody.closest('table'),wrap=table.closest('.table-wrap'),panel=table.closest('.panel');panel?.classList.add('qa-list-layout');const tools=node('div','qa-view-tools');tools.setAttribute('aria-label',t('List view'));const cards=node('div','qa-cards');let view=storage('qa.list-view')||(innerWidth<=620?'cards':'table');const buttons={};for(const mode of ['cards','table']){const b=node('button','',t(mode==='cards'?'Cards':'Table'));b.type='button';b.onclick=()=>{view=mode;storage('qa.list-view',mode);render()};tools.append(b);buttons[mode]=b}wrap.before(tools);wrap.after(cards);
function render(){const rows=[...tbody.rows];const headers=[...table.tHead.rows[0].cells];cards.replaceChildren();for(const row of rows){if(row.cells.length<2){cards.append(node('p','muted',row.textContent));continue}const card=node('article','qa-list-card');const code=node('a','qa-card-code qa-record-name',row.cells[0].textContent);code.href=row.querySelector('a')?.href||'#';let name=row.cells[1].childNodes[0]?.textContent?.trim();if(locale()==='bn'&&row.cells[1].querySelector('.muted')?.textContent)name=row.cells[1].querySelector('.muted').textContent;card.append(code,node('h3','qa-record-name',name));const data=fields(row,headers);const basics=node('div','qa-card-fields');[...data.children].filter((e,index)=>index<2||[...row.cells].slice(2)[index]?.dataset.col==='phone').forEach(e=>basics.append(e.cloneNode(true)));card.append(basics);const details=node('details');details.append(node('summary','',t('Details')),data);card.append(details);const actions=node('div','qa-card-footer');const open=node('a','',t('Open Profile'));open.href=code.href;actions.append(open);for(const source of row.querySelectorAll('td[data-col="access"] button,td[data-col="access"] a')){const b=node('button','',source.textContent);b.type='button';b.disabled=source.disabled;b.onclick=()=>source.click();actions.append(b)}if(innerWidth>1100){const peek=node('button','',t('Details'));peek.type='button';peek.onclick=()=>rail(row,headers);actions.append(peek)}card.append(actions);cards.append(card)}
buttons.cards.textContent=t('Cards');buttons.table.textContent=t('Table');buttons.cards.setAttribute('aria-pressed',String(view==='cards'));buttons.table.setAttribute('aria-pressed',String(view==='table'));wrap.classList.toggle('hidden',view==='cards');cards.classList.toggle('hidden',view!=='cards');}
new MutationObserver(render).observe(tbody,{childList:true,subtree:true,characterData:true});table.addEventListener('click',e=>{if(innerWidth<=1100||e.target.closest('a,button,select,input,thead'))return;const row=e.target.closest('tr');if(row&&row.cells.length>1)rail(row,[...table.tHead.rows[0].cells])});window.addEventListener('qa-language-change',render);window.addEventListener('resize',()=>{if(!storage('qa.list-view'))view=innerWidth<=620?'cards':'table';render()});render();}
const tabs=document.querySelector('.student-group-tabs,.staff-type-tabs,.staff-tabs');if(tabs){const student=!!$('studentListTab');for(const [label,href] of student?[['Teachers','staff.html#teachers'],['Helpers','staff.html#helpers']]:[['Students','students.html'],['Groups','students.html#groups']]){const a=node('a','qa-section-link qa-cross-tab',t(label));a.href=href;tabs.append(a);window.addEventListener('qa-language-change',()=>a.textContent=t(label))}if(student&&location.hash==='#groups')$('groupListTab')?.click();}}
export function mobileTables(){for(const table of document.querySelectorAll('#todayVoucherRows,#duesRows,#payrollRows,#paymentRows,#scheduleRows,#attendanceRows')){const t=table.closest('table');if(!t||t.querySelector('[rowspan]'))continue;t.classList.add('qa-table-mobile');const label=()=>{const headers=[...t.tHead?.rows[0]?.cells||[]];for(const row of table.rows)[...row.cells].forEach((cell,i)=>cell.dataset.label=headers[i]?.textContent||'')};new MutationObserver(label).observe(table,{childList:true,subtree:true});window.addEventListener('qa-language-change',label);label();}}

export function groupViews(){const list=document.getElementById('embeddedGroupList');if(!list)return;const tools=node('div','qa-view-tools'),buttons=new Map();let view=storage('qa.group-view')||(innerWidth<=620?'cards':'table');for(const mode of ['cards','table']){const b=node('button','',t(mode==='cards'?'Cards':'Table'));b.type='button';b.onclick=()=>{view=mode;storage('qa.group-view',mode);render()};buttons.set(mode,b);tools.append(b)}list.before(tools);function render(){list.classList.toggle('qa-group-cards',view==='cards');list.classList.toggle('qa-group-table',view==='table');buttons.forEach((b,mode)=>{b.textContent=t(mode==='cards'?'Cards':'Table');b.setAttribute('aria-pressed',String(view===mode))})}window.addEventListener('qa-language-change',render);window.addEventListener('resize',()=>{if(!storage('qa.group-view'))view=innerWidth<=620?'cards':'table';render()});render();}
