import {t} from './ui-i18n.js?v=20261001-fixes2';
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text)n.textContent=text;return n};
export function initPortals(){
 if(!document.body.classList.contains('portal-page'))return;
 document.body.classList.add('qa-portal-layout');compactPortalHeader();
 const app=document.getElementById('app'),teacher=location.pathname.includes('teacher-portal'),helper=location.pathname.includes('helper-portal');
 // Desktop tabs keep their existing order; mobile navigation has its own compact order.
 const groups=helper?['Summary','Information','Payroll','Documents']:teacher?['Summary','My Students','My Groups','Payroll','Information','Documents']:['Summary','Classes','Fees','Information','Documents'];
 const primary=helper?['Information','Summary','Payroll']:teacher?['Information','My Students','My Groups','Summary']:['Information','Classes','Summary','Fees'];
 const overflow=teacher?['Payroll','Documents']:['Documents'];
 const mobile=matchMedia('(max-width:620px)'),tabs=el('nav','qa-portal-tabs'),panes=new Map(),buttons=new Map();let current='Information';
 tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label',t('Portal'));
 groups.forEach((label,i)=>{
  const pane=el('div','qa-portal-pane hidden'),button=el('button','',t(label));
  pane.id='qa-pane-'+i;pane.setAttribute('role','tabpanel');button.id='qa-tab-'+i;button.type='button';button.dataset.portalTab=String(i);button.dataset.portalSection=label;
  button.style.setProperty('--portal-mobile-order',primary.indexOf(label));
  if(overflow.includes(label))button.classList.add('qa-portal-overflow');
  button.setAttribute('role','tab');button.setAttribute('aria-controls',pane.id);pane.setAttribute('aria-labelledby',button.id);
  panes.set(label,pane);buttons.set(label,button);tabs.append(button);button.onclick=()=>{activate(label);closeMore(false)};button.onkeydown=navigate;
 });
 const more=el('button','qa-portal-more',t('More'));more.type='button';more.dataset.portalSection='More';more.style.setProperty('--portal-mobile-order',primary.length);more.setAttribute('aria-haspopup','dialog');more.setAttribute('aria-controls','qa-portal-more-sheet');more.setAttribute('aria-expanded','false');more.onkeydown=navigate;tabs.append(more);
 const backdrop=el('div','qa-portal-more-backdrop'),sheet=el('section','qa-portal-more-sheet');sheet.id='qa-portal-more-sheet';sheet.hidden=true;backdrop.hidden=true;sheet.setAttribute('role','dialog');sheet.setAttribute('aria-modal','true');sheet.setAttribute('aria-labelledby','qa-portal-more-title');
 const handle=el('div','qa-portal-more-handle'),heading=el('div','qa-portal-more-head'),title=el('strong','',t('More')),close=el('button','','×');title.id='qa-portal-more-title';close.type='button';close.setAttribute('aria-label',t('Close'));heading.append(title,close);sheet.append(handle,heading);
 const menuButtons=new Map();overflow.forEach(label=>{const b=el('button','qa-portal-menu-item',t(label));b.type='button';b.dataset.portalSection=label;b.onclick=()=>{activate(label);closeMore(false);panes.get(label).setAttribute('tabindex','-1');panes.get(label).focus({preventScroll:true})};menuButtons.set(label,b);sheet.append(b)});
 const actions=document.querySelector('.portal-actions'),exit=document.getElementById('signOut'),whatsapp=document.getElementById('whatsappBtn'),name=document.querySelector('.portal-identity h1');
 const exitSlot=document.createComment('portal sign-out position'),whatsappSlot=document.createComment('portal WhatsApp position');exit?.before(exitSlot);whatsapp?.before(whatsappSlot);
 const nameRow=el('div','qa-portal-name-row');if(name){name.before(nameRow);nameRow.append(name)}
 function showBars(){tabs.classList.remove('is-hidden');tabs.inert=false;document.querySelector('.portal-head')?.classList.remove('is-mobile-hidden')}
 function closeMore(restore=true){const wasOpen=!sheet.hidden;sheet.hidden=true;backdrop.hidden=true;more.setAttribute('aria-expanded','false');if(wasOpen&&restore&&mobile.matches)more.focus({preventScroll:true})}
 function activate(label){current=label;groups.forEach(name=>{const active=name===label;panes.get(name).classList.toggle('hidden',!active);buttons.get(name).setAttribute('aria-selected',String(active));buttons.get(name).tabIndex=active?0:-1});more.classList.toggle('is-active',overflow.includes(label));more.tabIndex=mobile.matches&&overflow.includes(label)?0:-1;showBars()}
 function navigate(e){if(!['ArrowRight','ArrowLeft','Home','End'].includes(e.key))return;e.preventDefault();const available=[...tabs.children].filter(b=>!b.hidden&&(mobile.matches?!b.classList.contains('qa-portal-overflow'):b!==more));if(mobile.matches)available.sort((a,b)=>Number(a.style.getPropertyValue('--portal-mobile-order'))-Number(b.style.getPropertyValue('--portal-mobile-order')));let index=available.indexOf(e.currentTarget);index=e.key==='Home'?0:e.key==='End'?available.length-1:(index+(e.key==='ArrowRight'?1:-1)+available.length)%available.length;const target=available[index];if(target!==more)activate(target.dataset.portalSection);target.focus()}
 function update(){const payroll=app.querySelector('#teacherPayrollPanel,#helperPayrollPanel');if(payroll){const empty=payroll.classList.contains('hidden');buttons.get('Payroll').hidden=empty;if(menuButtons.has('Payroll'))menuButtons.get('Payroll').hidden=empty;if(empty&&current==='Payroll')activate('Information')}
  tabs.style.setProperty('--portal-tab-count',groups.filter(n=>!buttons.get(n).hidden).length);tabs.style.setProperty('--portal-mobile-count',primary.filter(n=>!buttons.get(n).hidden).length+1);
  // Keep a keyboard entry point in the visible primary row when an overflow pane is selected.
  more.tabIndex=mobile.matches&&overflow.includes(current)?0:-1;
 }
 function responsive(){closeMore(false);showBars();if(mobile.matches){if(exit){exit.classList.add('qa-portal-menu-item');sheet.append(exit)}if(whatsapp&&name)nameRow.append(whatsapp)}else{if(exit){exit.classList.remove('qa-portal-menu-item');exitSlot.after(exit)}if(whatsapp)whatsappSlot.after(whatsapp)}update()}
 more.onclick=()=>{if(!mobile.matches)return;const open=sheet.hidden;if(!open){closeMore();return}showBars();sheet.hidden=false;backdrop.hidden=false;more.setAttribute('aria-expanded','true');close.focus({preventScroll:true})};close.onclick=()=>closeMore();backdrop.onclick=()=>closeMore();exit?.addEventListener('click',()=>closeMore(false));
 sheet.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();closeMore()}else if(e.key==='Tab'){const controls=[...sheet.querySelectorAll('button,a')].filter(n=>!n.hidden&&n.getClientRects().length),first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
 const summary=app.querySelector(':scope>.portal-summary-grid');if(summary)panes.get('Summary').append(summary);
 for(const panel of [...app.querySelectorAll('.portal-panel')]){let label='Information';if(panel.querySelector('.document-manager'))label='Documents';else if(panel.querySelector('#assignedStudentRows'))label='My Students';else if(panel.querySelector('#groupRows'))label='My Groups';else if(panel.querySelector('#payrollRows'))label='Payroll';else if(panel.querySelector('#paymentRows,#fees'))label='Fees';else if(panel.querySelector('#scheduleRows,#attendanceRows,#enrollments,#assignedTeacher'))label='Classes';else if(panel.querySelector('#notes'))label='Summary';(panes.get(label)||panes.get('Information')).append(panel)}
 app.querySelector('.portal-hero').after(tabs,...panes.values());app.querySelectorAll(':scope>.portal-grid').forEach(n=>{if(!n.children.length)n.remove()});document.body.append(backdrop,sheet);activate('Information');
 const payroll=app.querySelector('#teacherPayrollPanel,#helperPayrollPanel');if(payroll)new MutationObserver(update).observe(payroll,{attributes:true,attributeFilter:['class']});mobile.addEventListener('change',responsive);responsive();
 let lastY=scrollY;window.addEventListener('scroll',()=>{if(!mobile.matches)return;const y=scrollY;if(y<40||y<lastY-7)showBars();else if(y>lastY+9&&y>120&&sheet.hidden){tabs.classList.add('is-hidden');tabs.inert=true;document.querySelector('.portal-head')?.classList.add('is-mobile-hidden')}lastY=y},{passive:true});
 tabs.addEventListener('focusin',showBars);
 window.addEventListener('qa-language-change',()=>{buttons.forEach((b,label)=>b.textContent=t(label));menuButtons.forEach((b,label)=>b.textContent=t(label));more.textContent=t('More');title.textContent=t('More');close.setAttribute('aria-label',t('Close'));tabs.setAttribute('aria-label',t('Portal'))});
}
export function profileReadMode(){const head=document.querySelector('.profile-head');if(!head)return;head.classList.add('qa-profile-hero');const identity=head.firstElementChild;identity?.classList.add('profile-identity');const photo=identity?.querySelector('.profile-photo-box');if(photo){head.prepend(photo);photo.classList.add('qa-profile-photo')}const update=()=>{const edit=!!document.getElementById('saveBtn')&&!document.getElementById('saveBtn').classList.contains('hidden');document.querySelectorAll('.profile-body .field,.profile-card-body .profile-field,.guardian-inline-form label').forEach(field=>{const input=field.querySelector('input:not([type=file]),textarea,select');if(!input)return;let value=field.querySelector('.qa-read-value');if(!value){value=el('span','qa-read-value qa-record-name');input.after(value)}const text=input.tagName==='SELECT'?input.selectedOptions[0]?.textContent||'—':input.value||'—';if(value.textContent!==text)value.textContent=text;field.classList.toggle('qa-read-mode',!edit&&(input.disabled||input.readOnly));})};const observer=new MutationObserver(()=>{observer.disconnect();update();observe()});const observe=()=>observer.observe(document.getElementById('app'),{attributes:true,attributeFilter:['class','disabled','readonly'],childList:true,subtree:true});observe();document.addEventListener('change',update);window.addEventListener('qa-language-change',update);update();}

function compactPortalHeader(){const actions=document.querySelector('.portal-actions');if(!actions)return;const paths={signOut:'<path d="M10 4H4v16h6M13 8l4 4-4 4M8 12h12"/>',whatsappBtn:'<path d="M20.52 3.48A11.86 11.86 0 0 0 12.08 0C5.53 0 .2 5.33.2 11.88c0 2.1.55 4.15 1.59 5.96L.1 24l6.3-1.65a11.9 11.9 0 0 0 5.68 1.44h.01c6.55 0 11.88-5.33 11.88-11.88 0-3.17-1.24-6.15-3.45-8.43ZM12.09 21.8h-.01a9.88 9.88 0 0 1-5.03-1.38l-.36-.21-3.74.98 1-3.65-.23-.37a9.86 9.86 0 0 1-1.51-5.29C2.21 6.43 6.64 2 12.09 2c2.63 0 5.1 1.03 6.96 2.89a9.82 9.82 0 0 1 2.9 6.99c0 5.45-4.43 9.92-9.86 9.92Zm5.43-7.41c-.3-.15-1.77-.88-2.05-.98-.27-.1-.47-.15-.67.15-.2.3-.77.98-.94 1.18-.17.2-.35.22-.65.07-.3-.15-1.26-.46-2.4-1.47-.89-.79-1.49-1.76-1.66-2.06-.17-.3-.02-.46.13-.61.13-.13.3-.35.45-.52.15-.17.2-.3.3-.5.1-.2.05-.37-.03-.52-.07-.15-.67-1.61-.92-2.2-.24-.58-.49-.5-.67-.51-.17-.01-.37-.01-.57-.01-.2 0-.52.08-.79.37-.27.3-1.04 1.02-1.04 2.5s1.07 2.9 1.22 3.1c.15.2 2.1 3.21 5.08 4.5.71.31 1.26.49 1.69.62.71.23 1.36.2 1.87.12.57-.08 1.77-.72 2.02-1.41.25-.69.25-1.28.17-1.41-.07-.12-.27-.2-.57-.35Z"/>'};for(const [id,path] of Object.entries(paths)){const control=document.getElementById(id);if(!control)continue;const label=el('span','qa-portal-action-label',control.textContent.trim()),svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('fill',id==='whatsappBtn'?'currentColor':'none');svg.setAttribute('stroke',id==='whatsappBtn'?'none':'currentColor');svg.setAttribute('stroke-width','1.8');svg.setAttribute('aria-hidden','true');svg.innerHTML=path;control.replaceChildren(svg,label);control.setAttribute('aria-label',t(id==='signOut'?'Sign out':'School WhatsApp'));control.title=t(id==='signOut'?'Sign out':'School WhatsApp');}const exit=document.getElementById('signOut');if(exit)new MutationObserver(()=>{if(!exit.querySelector('svg')){const text=exit.textContent.trim(),svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('fill',id==='whatsappBtn'?'currentColor':'none');svg.setAttribute('stroke',id==='whatsappBtn'?'none':'currentColor');svg.setAttribute('stroke-width','1.8');svg.setAttribute('aria-hidden','true');svg.innerHTML=paths.signOut;exit.replaceChildren(svg,el('span','qa-portal-action-label',text));exit.setAttribute('aria-label',text);exit.title=text;}}).observe(exit,{childList:true});window.addEventListener('qa-language-change',()=>{for(const id of Object.keys(paths)){const c=document.getElementById(id);if(c){c.setAttribute('aria-label',t(id==='signOut'?'Sign out':'School WhatsApp'));c.title=c.getAttribute('aria-label')}}});}
