const {chromium}=require('playwright');
const fs=require('fs');
const path=require('path');
const repo=path.resolve(__dirname,'..');
const origin='http://127.0.0.1:8765';
const fixture={
 qa_users:[{user_id:'u1',email:'qa@example.test',full_name:'QA Owner',role:'owner',active:true}],
 qa_students:[{student_id:'s1',student_code:'QAS-26-001',full_name:'Abdullah Rahman',full_name_bn:'আব্দুল্লাহ রহমান',status:'active',gender:'male',monthly_fee:500,phone:'01700000001',user_id:'u1',teacher_id:'t1',admission_date:'2026-09-01',created_at:'2026-09-01'},{student_id:'s2',student_code:'QAS-26-002',full_name:'Fatima Ahmed',full_name_bn:'ফাতিমা আহমেদ',status:'inactive',gender:'female',monthly_fee:600,phone:'01700000002',admission_date:'2026-09-02',created_at:'2026-09-02'}],
 qa_teachers:[{teacher_id:'t1',teacher_code:'QAT-26-001',full_name:'Teacher Rahman',full_name_bn:'শিক্ষক রহমান',active:true,user_id:'u1',gender:'male',phone:'01700000003',joining_date:'2026-09-01',created_at:'2026-09-01',specialization:'HIFZ'}],
 qa_staff:[{staff_id:'h1',staff_code:'QAH-26-001',full_name:'Helper Hasan',full_name_bn:'হেল্পার হাসান',active:true,user_id:'u1',staff_type:'helper',gender:'male',phone:'01700000004',joining_date:'2026-09-01',created_at:'2026-09-01'}],
 qa_study_groups:[{group_id:'g1',group_name:'Hifz A',teacher_id:'t1',active:true,created_at:'2026-09-01'}],qa_group_memberships:[{group_id:'g1',student_id:'s1',left_at:null}],
 qa_enrollments:[{enrollment_id:'e1',student_id:'s1',course_code:'HIFZ',teacher_user_id:'u1',start_date:'2026-09-01',status:'active'}],
 qa_fee_charges:[{charge_id:'c1',student_id:'s1',billing_month:'2026-09-01',expected_amount:500,discount:0,current_payable:500,status:'partial',fee_category:'monthly',previous_due:0},{charge_id:'c2',student_id:'s2',billing_month:'2026-09-01',expected_amount:600,discount:0,current_payable:600,status:'open',fee_category:'monthly',previous_due:0}],
 qa_fee_payments:[{payment_id:'p1',charge_id:'c1',student_id:'s1',receipt_no:'FRC-QA-001',paid_at:'2026-10-01T06:00:00Z',amount:100,payment_method:'cash'}],
 qa_app_settings:[{key:'school_profile',value:{name_bn:'কোরআনের আলো',name_en:'QURANER ALO',phone:'01700000000'}},{key:'financial_settings',value:{opening_balance:1000}},{key:'document_storage_settings',value:{}}],
 qa_finance_transactions:[{transaction_id:'f1',transaction_date:'2026-10-01',direction:'income',category:'Donation',amount:200}],qa_payroll_records:[],qa_vouchers:[],qa_student_guardians:[],qa_guardians:[],qa_attendance_records:[],qa_class_sessions:[],qa_user_permissions:[],qa_permissions:[]
};
const mock=`const initial=${JSON.stringify(fixture)};
window.__db=structuredClone(initial);window.__writes=[];if(window.__empty){for(const t of ['qa_enrollments','qa_fee_charges','qa_fee_payments','qa_payroll_records','qa_class_sessions'])window.__db[t]=[];}else{window.__db.qa_enrollments[0].notes='Progress note';window.__db.qa_class_sessions=[{session_id:'cl1',course_code:'HIFZ',session_date:'2099-01-01',status:'scheduled',meeting_link:'https://example.test/class'}];window.__db.qa_payroll_records=[{payroll_id:'pr1',salary_month:'2026-09-01',status:'paid',net_salary:500,paid_amount:500}];}window.__deny=window.__deny||[];
class Q{constructor(table){this.table=table;this.filters=[];this.start=0;this.end=Infinity;this.one=false;}select(_,opts){this.opts=opts;return this;}eq(k,v){this.filters.push(r=>r[k]===v);return this;}neq(k,v){this.filters.push(r=>r[k]!==v);return this;}is(k,v){this.filters.push(r=>(r[k]??null)===v);return this;}in(k,v){this.filters.push(r=>v.includes(r[k]));return this;}gte(){return this;}lte(){return this;}ilike(){return this;}or(){return this;}not(){return this;}order(){return this;}limit(n){this.end=n-1;return this;}range(a,b){this.start=a;this.end=b;return this;}single(){this.one=true;return this;}maybeSingle(){this.one=true;return this;}insert(rows){this.op='insert';this.payload=Array.isArray(rows)?rows:[rows];return this;}update(data){this.op='update';this.payload=data;return this;}upsert(data){return this.insert(data);}delete(){this.op='delete';return this;}then(resolve,reject){try{if(window.__queryError&&this.table==='qa_fee_charges')return Promise.resolve({data:null,error:{message:'FIXTURE_QUERY_ERROR'}}).then(resolve,reject);let all=window.__db[this.table]||[],rows=all.filter(r=>this.filters.every(f=>f(r)));if(this.op==='insert'){if(this.table==='qa_fee_charges'&&this.payload.some(r=>window.__db.qa_students.find(s=>s.student_id===r.student_id)?.status!=='active'))return Promise.resolve({data:null,error:{message:'INACTIVE_STUDENT',code:'23514'}}).then(resolve,reject);const data=this.payload.map((r,i)=>({...r,charge_id:r.charge_id||'new-'+Date.now()+'-'+i,payment_id:r.payment_id||'p-new',receipt_no:'FRC-QA-NEW',status:'open'}));all.push(...data);window.__db[this.table]=all;window.__writes.push({table:this.table,rows:data});rows=data;}if(this.op==='update'){rows.forEach(r=>Object.assign(r,this.payload));window.__writes.push({table:this.table,data:this.payload});}const count=rows.length;rows=rows.slice(this.start,this.end+1);return Promise.resolve({data:this.one?rows[0]||null:rows,count,error:null}).then(resolve,reject);}catch(e){return Promise.reject(e).then(resolve,reject);}}}
const session={user:{id:'u1',email:'qa@example.test'},access_token:'qa-fixture'};
export function createClient(){return{from:t=>new Q(t),rpc:async(name,args)=>{if(name!=='qa_receive_fee_batch')return{data:[],error:null};const existing=window.__db.qa_fee_payments.filter(p=>p.batch_id===args.p_batch_id);if(existing.length)return{data:existing,error:null};const rows=args.p_items.map((x,i)=>({...x,payment_id:'pb'+i,batch_id:args.p_batch_id,student_id:args.p_student_id,amount:x.amount,paid_at:args.p_paid_at,payment_method:args.p_method,receipt_no:'QA-B-'+i}));window.__db.qa_fee_payments.push(...rows);window.__writes.push({table:'qa_fee_payments',rows});return{data:rows,error:null}},auth:{getSession:async()=>({data:{session:location.pathname.endsWith('index.html')?null:session},error:null}),getUser:async()=>({data:{user:session.user}}),signOut:async()=>({error:null}),onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}})},functions:{invoke:async(name,args)=>{if(name==='portal-self-payroll')return{data:{ok:true,payrolls:window.__db.qa_payroll_records,summary:{totalPaid:500}},error:null};if(name==='portal-teacher-student')return{data:{ok:true,teacher:window.__db.qa_teachers[0],students:window.__db.qa_students.slice(0,1)},error:null};const type=args?.body?.entityType,entities={student:window.__db.qa_students[0],teacher:window.__db.qa_teachers[0],helper:window.__db.qa_staff[0]};return{data:{ok:true,entityType:type,entity:entities[type],files:[],data:[]},error:null}}}}};`;
const docs=`export async function getProfileImage(){return{found:false}};export async function fetchDocumentBlob(){return{blob:new Blob()}};export async function setProfileImage(){return{found:false}};export function validateDocumentFile(){return true};export async function validateDocumentFileContent(){return true};export async function listDocuments(){return{files:[],storage:{}}};export async function uploadDocument(){return{}};export async function deleteDocument(){return{}};export async function openDocument(){return{}};export async function downloadDocument(){return{}};`;
async function setup(context){await context.route('https://cdn.jsdelivr.net/**',r=>r.fulfill({contentType:'application/javascript',body:r.request().url().includes('+esm')?mock:mock.replace('export function createClient','function createClient')+'window.supabase={createClient};'}));await context.route('**/authz.js*',r=>r.fulfill({contentType:'application/javascript',body:`export async function getAccess(){return{profile:{user_id:'u1',role:'owner',active:true},can:key=>!window.__deny?.includes(key)}}`}));await context.route('**/documents-client.js*',r=>r.fulfill({contentType:'application/javascript',body:docs}));await context.route('**/documents-ui.js*',r=>r.fulfill({contentType:'application/javascript',body:`export async function setProfileImage(){return{found:false}};export async function mountDocumentsPanel(o){const e=document.createElement('div');e.className='document-manager';e.textContent='Documents upload';e.dataset.editable=String(o.editable);o.container?.append?.(e);return e}` }));await context.route('**/dashboard-documents.js*',r=>r.fulfill({contentType:'application/javascript',body:''}));await context.route('https://fonts.googleapis.com/**',r=>r.fulfill({contentType:'text/css',body:''}));}
async function open(page,path){await page.goto(origin+'/'+path);await page.waitForTimeout(700);}
function assert(x,m){if(!x)throw Error(m)}
(async()=>{
 const server=require('http').createServer((req,res)=>{const p=path.join(repo,decodeURIComponent(req.url.split('?')[0]));try{res.setHeader('Content-Type',p.endsWith('.js')?'application/javascript':p.endsWith('.css')?'text/css':p.endsWith('.png')?'image/png':'text/html');res.end(fs.readFileSync(p));}catch{res.statusCode=404;res.end('Not found')}});await new Promise(r=>server.listen(8765,'127.0.0.1',r));
 const browser=await chromium.launch({executablePath:process.env.PORTAL_TEST_BROWSER||undefined,headless:true,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--no-zygote','--use-gl=disabled'],env:{...process.env,LD_LIBRARY_PATH:process.env.PORTAL_TEST_BROWSER_LIBS||process.env.LD_LIBRARY_PATH||''}});let count=0;const errors=[];
 for(const empty of [false,true])for(const role of ['student','teacher','helper'])for(const preview of [false,true]){
 const ctx=await browser.newContext({viewport:{width:1440,height:960}});await setup(ctx);await ctx.addInitScript(v=>{window.__empty=v;localStorage.setItem('qa_language','en')},empty);const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await open(page,`${role}-portal.html${preview?'?preview_'+role+'='+({student:'s1',teacher:'t1',helper:'h1'}[role]):''}`);
 assert(await page.locator('#app').isVisible(),role+' failed '+await page.locator('#errorBox').textContent());
 await page.locator('[data-language=en]').first().click();const tabs=page.locator('.qa-portal-tabs [role=tab]:visible');assert(await tabs.count()===(role==='student'?5:role==='teacher'?(empty?5:6):(empty?3:4)),'tab count '+role);
 const dup=await page.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(e=>e.id);return ids.filter((id,i)=>ids.indexOf(id)!==i)});assert(!dup.length,'duplicate IDs '+dup);
 if(role==='student'){
 for(const id of ['studentNotesPanel','studentEnrollmentPanel','studentSchedulePanel','studentFeesPanel','studentPaymentsPanel'])assert(await page.locator('#'+id).evaluate(e=>e.classList.contains('hidden'))===empty,'optional '+id);
 if(!empty){assert((await page.locator('#totalDue').textContent()).includes('400'),'fee totals changed');assert((await page.locator('#paymentRows a').first().getAttribute('href')).includes('type=fee&id=p1'),'fee receipt changed');}
 await page.click('[data-portal-section=Classes]');assert(await page.locator('#assignedTeacher').isVisible(),'core teacher absent');if(!empty){const w=await page.locator('#assignedTeacher').boundingBox(),card=await page.locator('#assignedTeacher .assigned-person-card').boundingBox();assert(card.width>w.width-3,'teacher card still undersized');}assert(await page.locator('#attendanceRows').isVisible(),'attendance absent');
 await page.click('[data-portal-section=Information]');assert(await page.locator('#guardians').isVisible(),'guardian absent');
 }else{
 assert(await page.locator('#'+role+'PayrollPanel').evaluate(e=>e.classList.contains('hidden'))===empty,'payroll hidden');
 if(role==='teacher'){await page.click('[data-portal-section="My Groups"]');assert(await page.locator('#groupRows').isVisible(),'assigned group absent');if(!preview){await page.click('#groupAttendanceToggle');assert(await page.locator('#groupAttendanceDateWrap').isVisible(),'attendance mode broken');}else assert(await page.locator('#groupAttendanceToggle').evaluate(e=>e.classList.contains('hidden')),'preview attendance writable');}
 }
 await tabs.first().focus();await page.keyboard.press('End');assert(await page.locator('[data-portal-section=Documents]').getAttribute('aria-selected')==='true','keyboard skipped visible tab');await page.click('[data-portal-section=Documents]');assert(await page.locator('.document-manager').first().isVisible(),'documents absent');assert(await page.locator('.document-manager[data-editable]').getAttribute('data-editable')===String(!preview),'document edit permission changed');assert((await page.locator('#whatsappBtn').getAttribute('href')).includes('01700000000'),'school WhatsApp changed');
 for(const width of [320,390,820,1440]){
 await page.setViewportSize({width,height:960});for(let i=0;i<await tabs.count();i++){await tabs.nth(i).click();assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),'overflow '+role+' '+width+' '+i);}
 const boxes=await tabs.evaluateAll(es=>es.map(e=>e.getBoundingClientRect().width));assert(Math.max(...boxes)-Math.min(...boxes)<2,'uneven tabs');assert(await page.locator('.qa-portal-tabs').evaluate(e=>getComputedStyle(e).position)===(width<621?'fixed':'static'),'mobile nav placement');
 if(!empty&&!preview&&width===390){await page.click('[data-portal-section="'+(role==='student'?'Classes':'Summary')+'"]');if(process.env.PORTAL_TEST_SCREENSHOTS){fs.mkdirSync(process.env.PORTAL_TEST_SCREENSHOTS,{recursive:true});await page.screenshot({path:path.join(process.env.PORTAL_TEST_SCREENSHOTS,role+'-mobile.png'),fullPage:true});}}
 }
 await ctx.close();console.log('PASS',role,{empty,preview});count++;
 }
 const ctx=await browser.newContext();await setup(ctx);await ctx.addInitScript(()=>window.__queryError=true);const p=await ctx.newPage();await open(p,'student-portal.html');assert(await p.locator('#errorBox').isVisible(),'query error silently hidden');assert(!await p.locator('#app').isVisible(),'failed query treated as empty success');await ctx.close();assert(!errors.length,'JS errors '+errors.join(';'));console.log('PASS ALL',count,'portal scenarios + error path');await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1)});
